config/routes.rb
Locoto::Application.routes.draw do
  resources :restrooms

  resources :beacons

  resources :buildings

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  belongs_to :building
end

app/models/building.rb
class Building < ActiveRecord::Base
end

app/models/restroom.rb
class Restroom < ActiveRecord::Base
  belongs_to :building
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]

  # GET /beacons
  # GET /beacons.json
  def index
    @beacons = Beacon.all
  end

  # GET /beacons/1
  # GET /beacons/1.json
  def show
  end

  # GET /beacons/new
  def new
    @beacon = Beacon.new
  end

  # GET /beacons/1/edit
  def edit
  end

  # POST /beacons
  # POST /beacons.json
  def create
    @beacon = Beacon.new(beacon_params)

    respond_to do |format|
      if @beacon.save
        format.html { redirect_to @beacon, notice: 'Beacon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beacon }
      else
        format.html { render action: 'new' }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beacons/1
  # PATCH/PUT /beacons/1.json
  def update
    respond_to do |format|
      if @beacon.update(beacon_params)
        format.html { redirect_to @beacon, notice: 'Beacon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beacons/1
  # DELETE /beacons/1.json
  def destroy
    @beacon.destroy
    respond_to do |format|
      format.html { redirect_to beacons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beacon
      @beacon = Beacon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beacon_params
      params.require(:beacon).permit(:identifier, :prox_min, :prox_max, :prox_med, :building_id)
    end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render action: 'show', status: :created, location: @building }
      else
        format.html { render action: 'new' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :address)
    end
end

app/controllers/restrooms_controller.rb
class RestroomsController < ApplicationController
  before_action :set_restroom, only: [:show, :edit, :update, :destroy]

  # GET /restrooms
  # GET /restrooms.json
  def index
    @restrooms = Restroom.all
  end

  # GET /restrooms/1
  # GET /restrooms/1.json
  def show
  end

  # GET /restrooms/new
  def new
    @restroom = Restroom.new
  end

  # GET /restrooms/1/edit
  def edit
  end

  # POST /restrooms
  # POST /restrooms.json
  def create
    @restroom = Restroom.new(restroom_params)

    respond_to do |format|
      if @restroom.save
        format.html { redirect_to @restroom, notice: 'Restroom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @restroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restrooms/1
  # PATCH/PUT /restrooms/1.json
  def update
    respond_to do |format|
      if @restroom.update(restroom_params)
        format.html { redirect_to @restroom, notice: 'Restroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restrooms/1
  # DELETE /restrooms/1.json
  def destroy
    @restroom.destroy
    respond_to do |format|
      format.html { redirect_to restrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restroom
      @restroom = Restroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restroom_params
      params.require(:restroom).permit(:numbered, :typ, :building_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/restrooms_helper.rb
module RestroomsHelper
end

app/views/beacons/_form.html.erb
<%= form_for(@beacon) do |f| %>
  <% if @beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% @beacon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :prox_min %><br>
    <%= f.text_field :prox_min %>
  </div>
  <div class="field">
    <%= f.label :prox_max %><br>
    <%= f.text_field :prox_max %>
  </div>
  <div class="field">
    <%= f.label :prox_med %><br>
    <%= f.text_field :prox_med %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.text_field :building_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing beacon</h1>

<%= render 'form' %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Back', beacons_path %>

app/views/beacons/index.html.erb
<h1>Listing beacons</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Prox min</th>
      <th>Prox max</th>
      <th>Prox med</th>
      <th>Building</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.identifier %></td>
        <td><%= beacon.prox_min %></td>
        <td><%= beacon.prox_max %></td>
        <td><%= beacon.prox_med %></td>
        <td><%= beacon.building %></td>
        <td><%= link_to 'Show', beacon %></td>
        <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
        <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beacon', new_beacon_path %>

app/views/beacons/new.html.erb
<h1>New beacon</h1>

<%= render 'form' %>

<%= link_to 'Back', beacons_path %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @beacon.identifier %>
</p>

<p>
  <strong>Prox min:</strong>
  <%= @beacon.prox_min %>
</p>

<p>
  <strong>Prox max:</strong>
  <%= @beacon.prox_max %>
</p>

<p>
  <strong>Prox med:</strong>
  <%= @beacon.prox_med %>
</p>

<p>
  <strong>Building:</strong>
  <%= @beacon.building %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.address %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @building.address %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locoto</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restrooms/_form.html.erb
<%= form_for(@restroom) do |f| %>
  <% if @restroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restroom.errors.count, "error") %> prohibited this restroom from being saved:</h2>

      <ul>
      <% @restroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numbered %><br>
    <%= f.number_field :numbered %>
  </div>
  <div class="field">
    <%= f.label :typ %><br>
    <%= f.text_field :typ %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.text_field :building_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restrooms/edit.html.erb
<h1>Editing restroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @restroom %> |
<%= link_to 'Back', restrooms_path %>

app/views/restrooms/index.html.erb
<h1>Listing restrooms</h1>

<table>
  <thead>
    <tr>
      <th>Numbered</th>
      <th>Typ</th>
      <th>Building</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restrooms.each do |restroom| %>
      <tr>
        <td><%= restroom.numbered %></td>
        <td><%= restroom.typ %></td>
        <td><%= restroom.building %></td>
        <td><%= link_to 'Show', restroom %></td>
        <td><%= link_to 'Edit', edit_restroom_path(restroom) %></td>
        <td><%= link_to 'Destroy', restroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restroom', new_restroom_path %>

app/views/restrooms/new.html.erb
<h1>New restroom</h1>

<%= render 'form' %>

<%= link_to 'Back', restrooms_path %>

app/views/restrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numbered:</strong>
  <%= @restroom.numbered %>
</p>

<p>
  <strong>Typ:</strong>
  <%= @restroom.typ %>
</p>

<p>
  <strong>Building:</strong>
  <%= @restroom.building %>
</p>

<%= link_to 'Edit', edit_restroom_path(@restroom) %> |
<%= link_to 'Back', restrooms_path %>